### PR TITLE
Returning an array of Transitions from PendingTransactions -> get

### PR DESCRIPTION
**Pull request by charj**
A great spot by @kgdiem. It was noticed that `array_walk` returns a bool and we were returning this value, assuming it would return an array.

This test covers that problem and will check for the expected keys.

This test will fail currently, until #6 is merged.

### CODE REVIEW

**Comment by charj** [comment]
@kgdiem Have tested your code with my test and it passes :+1: 
Please could you do the same and just give this a once over?

**Comment by charj** [comment]
Causes the following failure:
`Time: 32 ms, Memory: 6.00MB

There was 1 failure:

1) PendingTransactionsTest::testGetReturnsAnArrayAndNotABoolean
Failed asserting that true is not of type "bool".

/home/charj/code/TrueLayer/tests/Bank/Account/PendingTransactionsTest.php:43

**Comment by charj** [comment]
It's suddenly dawned on me that PendingTransactions -> get() should return an array of `Transactions`, previously it's just returning the decoded json data and not the objects we expect.

Maybe I'm totally wrong here. Feel free to call me out if so!

**Comment by kgdiem** [comment]
thanks for picking up my slack here @charj

**Pull request merged**
